<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('album', ['action' => 'add']) ?>">Add new album</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Date</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($albums as $album) : ?>
        <tr>
            <td><?= $this->escapeHtml($album->title) ?></td>
            <td><?= $this->escapeHtml($album->artist) ?></td>
            <td><?= $this->escapeHtml($album->date) ?></td>
            <td>
                <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $album->id]) ?>">Edit</a>
                <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $album->id]) ?>">Delete</a>
                <a id="<?=$album->id?>" onclick="del(this)">Instant Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script>
     function del(row){
         var id= $(row).attr('id');
        // alert(id);
       $.ajax({
           url:"/album/remove",
           type:"POST",
           data:{
               id:id
           },
           success: function(data){
               $(row).parents("tr").remove()
           }
        });

       }
</script>